### PR TITLE
Fix redirects for campaign registration

### LINKED ISSUE #492: Campaign registration wrong code redirect
## Description

When inputting a wrong code while trying to join a campaign, the page is blank

## Expected Behavior

Should redirect to index page if the code doesn't exist

## Actual Behavior

Goes to the page anyways but typescript errors blocks page from rendering

## Steps to Reproduce

1. Go to campaign index 
2. Click join
3. Enter random code

## Possible Fix

In campaign registration controller, if the code is not valid, redirect to the index page or simply do a reload

# Other

### PR DESCRIPTION
**Pull request by m-triassi**
## Description
Closes #492 

Adjusts redirects when joining or creating campaigns to redirect to the appropriate place and return errors where appropriate

### CODE REVIEW

**Review by willyyhuang — APPROVED** [review]
lgtm!

File: app/Http/Controllers/CampaignRegistrationController.php [hunk 1]
```diff
@@ -24,6 +24,10 @@ public function create(Request $request)
 
         $campaign = Campaign::with('characters', 'users')->where('code', $code)->first();
 
+        if (!$campaign) {
+            return redirect()->back()->withErrors(['error' => "The provided campaign code is incorrect."]);
+        }
```
Comment (JasonGadoury) [inline app/Http/Controllers/CampaignRegistrationController.php:29]: I don't see a test for this, I'm guessing since coverage isn't checked on this PR? Would probably only need 4-5 lines of code.

**Review by JasonGadoury — APPROVED** [review]
Looks fine, don't see a test for the added branch. It may or may not be negligible once feat is merged into main, your call. Should be good to merge either way.

File: app/Http/Controllers/CampaignRegistrationController.php (hunk 1 above)
Comment (m-triassi) [reply app/Http/Controllers/CampaignRegistrationController.php:29]: Just added it :) good  catch!
