### PR TITLE
190 item import fix

### LINKED ISSUE #190: Remove deprecated "counted" field from AL item import
## Description

Al importer uses deprecated "counted" field when creating imported items. Should be removed.

### PR DESCRIPTION
**Pull request by IanjhPhillips**
## Description
closes #190 
- removes deprecated field manipulation
- refactors entry data by extracting to method call

### CODE REVIEW

**Comment by m-triassi** [comment]
Just a comment, before i do any reviewing, for your conventional commit label you can use `refactor: #190 reduce...` instead of `chore: #190 reduce...` in the future ;) especially since that was definitely a method extraction refactor

File: app/Services/AdventuresLeagueAdapter.php [hunk 1]
```diff
@@ -153,12 +127,43 @@ private function getEntries($data, $characterId)
...
+            return array_merge($entryData, $defaultEntryData);
+        } else {
+            $populatedEntryData = [
+                'dungeon_master' => (array_key_exists(12, $data)) ? (float)$data[12] : "",
+                'location' => (array_key_exists(11, $data)) ? (float)$data[11] : "",
+                'date_played' => ($data[3] == "") ? now() : $data[3],
+                'gp' => (array_key_exists(7, $data)) ? (float)$data[7] : 0,
+                'downtime' => (array_key_exists(8, $data)) ? (float)$data[8] : 0,
+                'type' => $type,
+            ];
```
Comment (m-triassi) [inline app/Services/AdventuresLeagueAdapter.php:165]: might be more readable to wrap `$data` in a collection and then use the [`get()` method](https://laravel.com/docs/8.x/collections#method-get), but i'd say thats mostly a matter of opinion
```suggestion
            $data = collect($data)
            $populatedEntryData = [
                'dungeon_master' => (float) $data->get(12),
                'location' => (float) $this->get(11),
                'date_played' => Carbon::parse($data->get(3)),
                'gp' => (float) $data->get(7, 0),
                'downtime' => (float) $data->get(8, 0),
                'type' => $type,
            ];
```

File: app/Services/AdventuresLeagueAdapter.php [hunk 2]
```diff
@@ -153,12 +127,43 @@ private function getEntries($data, $characterId)
...
+                'date_played' => now(),
+                'gp' => 0,
+                'downtime' => 0,
+                'type' => Entry::TYPE_GAME,
+            ];
+            return array_merge($entryData, $defaultEntryData);
+        } else {
+            $populatedEntryData = [
+                'dungeon_master' => (array_key_exists(12, $data)) ? (float)$data[12] : "",
+                'location' => (array_key_exists(11, $data)) ? (float)$data[11] : "",
```
Comment (m-triassi) [inline app/Services/AdventuresLeagueAdapter.php:160]: wait are these supposed to be cast to a float? dungeon master and location are supposed to be a strings describing either item

File: app/Services/AdventuresLeagueAdapter.php [hunk 3]
```diff
@@ -153,12 +127,43 @@ private function getEntries($data, $characterId)
...
                 ];
-                $item = new Item($itemData);
-                $item->save();
+                Item::create($itemData);
             }
         }
         return $entries;
     }
+
+    private function getEntryData($characterId, $data, $type)
```
Comment (m-triassi) [inline app/Services/AdventuresLeagueAdapter.php:137]: since you're checking data is null later in this function, we should probably define it as default null, same with type
```suggestion
    private function getEntryData($characterId, $data = null, $type = null)
```

File: app/Services/AdventuresLeagueAdapter.php [hunk 4]
```diff
@@ -105,39 +104,14 @@ private function getEntries($data, $characterId)
...
-                        'character_id' => $characterId,
-                        'event_id' => null,
-                        'dungeon_master_id' => null,
-                        'levels' => 0,
-                        'date_played' => now(),
-                        'gp' => 0,
-                        'downtime' => 0,
-                        'type' => Entry::TYPE_GAME,
-                    ]);
+                    $entryData = $this->getEntryData($characterId, null, null);
```
Comment (m-triassi) [inline app/Services/AdventuresLeagueAdapter.php:113]: if you set defaults in the evoked function signature this can just be 
```suggestion
                    $entryData = $this->getEntryData($characterId);
```

**Review by m-triassi — COMMENTED** [review]
Honestly i can probably approve here, imo, but let me know what you think of my suggestions first :)

**Review by RobertoNittolo — COMMENTED** [review]
Good Job, Great refactor! Pulled it locally everything looked good, just wasn't sure how to test it.

**Comment by RobertoNittolo** [comment]
> Good Job, Great refactor! Pulled it locally everything looked good, just wasn't sure how to test it.

I was able to find some previous instructions on how to test this from a previous PR. 

## How to test
pre-existing migration was modified so first:
`php artisan migrate:fresh`

then:
`php artisan tinker`
`$user = User::factory()->create()`
`Auth::login($user)`
`$character = AdventuresLeague::getCharacter(database_path("mocks/dante.csv"))`
observe that donte is imported, a character is created, and entries are attached.

observe the last entry and note down its id, ill refer to it as k, when you run the following command replace k with the id.
`$e = Entry::find(k)`
`$e->items`
observe the two items attached to this entry

File: app/Services/AdventuresLeagueAdapter.php (hunk 4 above)
Comment (pascwhale) [reply app/Services/AdventuresLeagueAdapter.php:113]: I never knew PHP had that feature! Thank you for mentioning it.

File: app/Services/AdventuresLeagueAdapter.php (hunk 2 above)
Comment (pascwhale) [reply app/Services/AdventuresLeagueAdapter.php:160]: Is dungeon master the ID of the dungeon master or a string to refer to that person (maybe not their actual name)? I also remember the D&D MTL talking about possibly not having accounts for someone acting as the DM.

File: app/Services/AdventuresLeagueAdapter.php (hunk 1 above)
Comment (pascwhale) [reply app/Services/AdventuresLeagueAdapter.php:165]: @m-triassi Can you tell me what happens if the index does not exist for a given collection through the get method? I couldn't find documentation online.

**Review by pascwhale — COMMENTED** [review]
I really liked the refactored code.

What I'd like to add on top of the other suggestions would be to avoid using indices to get specific columns values. If we know the default column names for this type of file using those names to get the column values might be safer and would make our code more readable.

I do not have enough experience using those CSV files though, and I don't know if the format might change. Maybe someone else would know.

File: app/Services/AdventuresLeagueAdapter.php (hunk 1 above)
Comment (m-triassi) [reply app/Services/AdventuresLeagueAdapter.php:165]: @pascwhale haha you didn't read closely enough, first line of the get methods docs:
> The get method returns the item at a given key. **If the key does not exist, null is returned**

File: app/Services/AdventuresLeagueAdapter.php (hunk 2 above)
Comment (m-triassi) [reply app/Services/AdventuresLeagueAdapter.php:160]: > Is dungeon master the ID of the dungeon master or a string to refer to that person

In this case its going to be their name as a string

> I also remember the D&D MTL talking about possibly not having accounts for someone acting as the DM.

Right, that's why in the database we have 2 fields, if the user is not present in our system then they can enter the string representation of the DMs name

File: app/Services/AdventuresLeagueAdapter.php (hunk 4 above)
Comment (m-triassi) [reply app/Services/AdventuresLeagueAdapter.php:113]: no problem :)

**Comment by m-triassi** [comment]
> What I'd like to add on top of the other suggestions would be to avoid using indices to get specific columns values

@pascwhale I can answer this for Ian, sadly, we are forces to use a specific index given the state of the CSV that the ALL site produces, it's quite _ahem_ non-standard...

File: app/Services/AdventuresLeagueAdapter.php (hunk 2 above)
Comment (IanjhPhillips) [reply app/Services/AdventuresLeagueAdapter.php:160]: not sure why these are being cast to float here, as you said they should be strings

File: app/Services/AdventuresLeagueAdapter.php (hunk 4 above)
Comment (IanjhPhillips) [reply app/Services/AdventuresLeagueAdapter.php]: great suggestion, added!

File: app/Services/AdventuresLeagueAdapter.php (hunk 3 above)
Comment (IanjhPhillips) [reply app/Services/AdventuresLeagueAdapter.php]: done!

File: app/Services/AdventuresLeagueAdapter.php (hunk 2 above)
Comment (IanjhPhillips) [reply app/Services/AdventuresLeagueAdapter.php]: fixed.

File: app/Services/AdventuresLeagueAdapter.php (hunk 1 above)
Comment (IanjhPhillips) [reply app/Services/AdventuresLeagueAdapter.php]: I like this implementation, its a lot cleaner. I added it. Thanks!

**Review by m-triassi — APPROVED** [review]
Excellent stuff! :) No more comments on my end, lets merge it 🚀
