### PR TITLE
Redirect to campaign detail upon entry creation

### LINKED ISSUE #500: Incorrect redirects after creating entry or DM entry
## Description

- In the campaign details page, there is a entry button in order to create an entry. After clicking on it, filling the entry form and clicking create, the user is incorrectly redirected to the (assigned)character's detail page.
- In the campaign details page, there is a DM entry button in order to create an entry. After clicking on it, filling the DM entry form and clicking create, the user is incorrectly redirected to the DM entry index page.

## Expected Behavior

After creating an entry or a DM entry, the user should be redirected to the campaign details page if they initially clicked on entry and DM entry buttons there.

## Steps to Reproduce

For Entry
1. Create a campaign with assigned character
2. Click on campaign (go to its detail page)
3. Create an entry and click create
4. You are now incorrectly redirected
For DM Entry
1. Create a campaign
2. Click on campaign (go to its detail page)
3. Create a DM entry and click create
4. You are now incorrectly redirected

## Possible Fix

# Other

### PR DESCRIPTION
**Pull request by JasonGadoury**
### Description
Closes #500 

Once a  **campaign**  entry or dm entry is successfully created, the user is now redirected to the campaign detail page instead of the character detail or dm entry index pages respectively.

To test:
1. Seed database
2. Create a dm entry for a campaign the signed in user is dm for
(if they are not dm for any campaign, create a campaign and assign them dm)
3. Observe that you have been redirected to campaign detail page
4. Create an entry for a campaign the signed in user is participating in with a character
5. Observe that you have been redirected to campaign detail page

### CODE REVIEW

**Comment by JasonGadoury** [comment]
Looks like I have a code smell for having too many redirects in the store function. Each redirect is chosen based on the type of entry being created (invalid gm entry, regular or dm entry with campaign, regular or dm w/o campaign...). The two options are to either ignore it or sacrifice one of the redirects. Thoughts? @m-triassi

**Comment by m-triassi** [comment]
@JasonGadoury there's a third option, instead of returning, assign the route name string to a variable that changes based on the conditions, and then pass that variable to the `route()` function
something like:
```php
if ($x == "Condition A") {
    $redirect = 'campaign.show';
    $extraData = [...];
} elseif ($x == "Condition B") {
    $redirect = 'character.index'; 
    $extraData = null;
}

return redirect()->route($redirect, $extraData);
```

File: app/Http/Controllers/EntryController.php [hunk 1]
```diff
@@ -97,11 +100,20 @@ public function store(EntryStoreRequest $request)
...
+            $redirectRoute = 'campaign.show';
+            $parameter = $campaign;
+        } elseif (!isset($campaign)) {
+            if ($entryData['type'] === Entry::TYPE_DM) {
+                $redirectRoute = 'dm-entry.index';
+                $parameter = null;
+            } else {
+                $redirectRoute = 'character.show';
+                $parameter = $entry->character_id;
+            }
```
Comment (m-triassi) [inline app/Http/Controllers/EntryController.php:113]: Typically i'd avoid nesting control flow logic more than 1 layer deep if possible. Since we don't really have the luxary of time, ill just say this is a refactor target and move on

**Review by m-triassi — APPROVED** [review]
This works, some things to consider for refactor, but I'll handle that at a later date.
