### PR TITLE
Event Detail and Registration

### LINKED ISSUE #426: Event detail and registration
## Description

[Figma link](https://www.figma.com/file/5uF4bHcHFTm13iMyrBzMt0/Designs-and-Mockups?node-id=1275%3A37216)

### LINKED ISSUE #473: Event Index uses wrong property for start date
## Description

The event index table uses the wrong data value for the start date.

## Expected Behavior

It should use the first date from the `scheduled_dates` array passed in the props.

## Actual Behavior

It uses the `created_at` property.

## Steps to Reproduce

1. Open the event index page and inspect the props being passed.

## Possible Fix

Use the first date in the `scheduled_dates` array being passed in from the component props.

# Other

### PR DESCRIPTION
**Pull request by pascwhale**
Closes #426 
Closes #473

## Description
- Add event detail page
- Connect to backend for user registration

### CODE REVIEW

File: resources/js/Components/Table/EventTable/EventTable.tsx [hunk 1]
```diff
@@ -1,18 +1,44 @@
...
+        />,
+    ]
 
     const columns = [
         {
-            property: 'created_at',
+            property: 'scheduled_dates',
             title: t('tableColumn.date'),
+            render: (value: string) => (
+                <Typography>{dayjs(value[0]).format('LLL')}</Typography>
```
Comment (willyyhuang) [inline resources/js/Components/Table/EventTable/EventTable.tsx:40]: why are we doing `value[0]` here?

File: resources/js/Components/Table/EventTable/EventTable.tsx [hunk 2]
```diff
@@ -28,13 +54,35 @@ const EventTable = ({data}: EventTablePropType) => {
             title: t('eventDetail.description'),
         },
         {
-            property: 'participation',
+            property: 'is_registered',
             title: t('tableColumn.participation'),
+            render: (value: boolean) =>
+                value ? (
```
Comment (willyyhuang) [inline resources/js/Components/Table/EventTable/EventTable.tsx:60]: you can do this instead, 
```
value && <Chip ....
```

Comment (willyyhuang) [reply resources/js/Components/Table/EventTable/EventTable.tsx:60]: unnecessary ternary makes code complicated for no reason

File: resources/js/Components/Detail/EventDetailBox.tsx [hunk 3]
```diff
@@ -0,0 +1,69 @@
+import {Box, Grid, Typography} from '@mui/material'
+import dayjs from 'dayjs'
+import React from 'react'
+import {useTranslation} from 'react-i18next'
+import styled from 'styled-components'
+import {EventData} from 'Types/event-data'
+// import route from 'ziggy-js'
```
Comment (willyyhuang) [inline resources/js/Components/Detail/EventDetailBox.tsx:7]: remove comment

File: resources/js/Components/Table/SessionTable/SessionTable.tsx [hunk 4]
```diff
@@ -0,0 +1,141 @@
...
+import {adventureType} from 'Types/adventure-data'
+import {CharacterData} from 'Types/character-data'
+import {UserType} from 'Types/global'
+import {SessionData} from 'Types/session-data'
+import route from 'ziggy-js'
+
+type SessionPropType = {
+    data: SessionData[]
+    eventID: number
+    setData: any
```
Comment (willyyhuang) [inline resources/js/Components/Table/SessionTable/SessionTable.tsx:16]: let's type these

File: resources/js/Components/Table/EventTable/EventTable.tsx [hunk 5]
```diff
@@ -1,18 +1,44 @@
...
 import {EventData} from 'Types/event-data'
+import route from 'ziggy-js'
 
 type EventTablePropType = {
     data: EventData[]
+    registered_only: boolean | null
 }
 
-const EventTable = ({data}: EventTablePropType) => {
+const EventTable = ({data, registered_only}: EventTablePropType) => {
```
Comment (willyyhuang) [inline resources/js/Components/Table/EventTable/EventTable.tsx:16]: i assume by default if `registered_only` is null, it means it's false right?

then this case we can initialize `registered_only` to false, you can do this by 

`const EventTable = ({data, registered_only = false}: EventTablePropType) => {`

File: resources/js/Components/Table/SessionTable/SessionTable.tsx [hunk 6]
```diff
@@ -0,0 +1,141 @@
...
+            title: t('tableColumn.seats-taken'),
+        },
+        {
+            property: 'seats_left',
+            title: t('tableColumn.seats-left'),
+        },
+        {
+            property: 'characters',
+            title: t('form.chosen-character'),
+            render: (value: CharacterData[]) => <Typography>{value[0]?.name}</Typography>,
```
Comment (willyyhuang) [inline resources/js/Components/Table/SessionTable/SessionTable.tsx:92]: chosen character is always the first one in `characters`?

File: resources/js/Components/Table/SessionTable/SessionTable.tsx [hunk 7]
```diff
@@ -0,0 +1,141 @@
...
+        },
+        {
+            property: 'is_registered',
+            title: t('tableColumn.actions'),
+            render: (value: boolean, row: SessionData) =>
+                value ? (
+                    <Button
```
Comment (willyyhuang) [inline resources/js/Components/Table/SessionTable/SessionTable.tsx:99]: instead of 2 buttons, use ternary within the props to conditionally determine which prop it is

for example

`color={value ? 'error' : 'primary'}

File: resources/js/Pages/Event/Detail/EventDetail.tsx [hunk 8]
```diff
@@ -1,19 +1,193 @@
...
+    allUserCharacters,
+    event,
+    registered_sessions,
+    sessions,
+}: EventDetailPropType) => {
+    const [isRegisterOpen, setIsRegisterFormOpen] = useState<boolean>(false)
+    const [isRegistered, setIsRegistered] = useState<boolean>(false)
+    const SESSION_REGISTRATION_FORM_INITIAL_VALUE = {
+        event_id: event.id,
+        session_id: 0,
```
Comment (willyyhuang) [inline resources/js/Pages/Event/Detail/EventDetail.tsx:55]: don't initialize form values to 0, make them undefined

File: resources/js/Pages/Event/Detail/EventDetail.tsx [hunk 9]
```diff
@@ -1,19 +1,193 @@
...
+        if (wasSuccessful) {
+            clearErrors()
+            setIsRegisterFormOpen(false)
+        }
+    }, [wasSuccessful])
+
     return (
         <ThemeProvider theme={getFontTheme('Form', 14, language)}>
-            <Typography>Event {event.id} is under construction</Typography>
+            <Modal
```
Comment (willyyhuang) [inline resources/js/Pages/Event/Detail/EventDetail.tsx:79]: i would extract the entire modal somewhere else

File: resources/js/Pages/Event/Detail/EventDetail.tsx [hunk 10]
```diff
@@ -1,19 +1,193 @@
...
+                                                errors?.overlap ||
+                                                errors?.seats
+                                            }
+                                        />
+                                    )}
+                                </Grid>
+                            )}
+                            <Grid item md={6}>
+                                {isRegistered ? (
+                                    <Button
```
Comment (willyyhuang) [inline resources/js/Pages/Event/Detail/EventDetail.tsx:129]: use ternary on props instead

**Review by willyyhuang — CHANGES_REQUESTED** [review]

File: resources/js/Components/Modal/EventRegistrationModal.tsx [hunk 11]
```diff
@@ -0,0 +1,165 @@
...
+                            </Grid>
+                        )}
+                        <Grid item md={6}>
+                            {registrationData.is_registered ? (
+                                <Button
+                                    loading={processing}
+                                    variant='contained'
+                                    fullWidth
+                                    onClick={() => {
+                                        if (data.session_id) {
```
Comment (willyyhuang) [inline resources/js/Components/Modal/EventRegistrationModal.tsx:128]: this if statement is not needed anymore

File: resources/js/Components/Modal/EventRegistrationModal.tsx [hunk 12]
```diff
@@ -0,0 +1,165 @@
...
+                                            errors?.overlap ||
+                                            errors?.seats
+                                        }
+                                    />
+                                )}
+                            </Grid>
+                        )}
+                        <Grid item md={6}>
+                            {registrationData.is_registered ? (
+                                <Button
```
Comment (willyyhuang) [inline resources/js/Components/Modal/EventRegistrationModal.tsx:123]: still, let's refactor this button to use ternary in props

**Review by willyyhuang — COMMENTED** [review]
few things

File: resources/js/Components/Table/EventTable/EventTable.tsx (hunk 5 above)
Comment (pascwhale) [reply resources/js/Components/Table/EventTable/EventTable.tsx:16]: Interesting, thank you

File: resources/js/Components/Table/SessionTable/SessionTable.tsx (hunk 7 above)
Comment (pascwhale) [reply resources/js/Components/Table/SessionTable/SessionTable.tsx:97]: This makes sense, thanks for pointing it out!

File: resources/js/Components/Modal/EventRegistrationModal.tsx (hunk 11 above)
Comment (pascwhale) [reply resources/js/Components/Modal/EventRegistrationModal.tsx:128]: I'm still getting an eslint error on this. I might keep it.

**Review by willyyhuang — APPROVED** [review]
everything looks good!
